APP_NAME = FlippeRPG

APP_SOURCE = FlippeRPG.c \
    codex/codex.c \
    signal/signal_engine.c \
    xp/xp_engine.c \
    shrine/shrine.c \
    duel/duel.c \
    save/save_system.c \
    core/utils.c

include $(FLIPPER_PATH)/applications/api.mk